class Album {

   String id;
   String titulo;
   String artista;
   String descripcion;
   String adicional;
   int year;
   String tapaUrl;

    Album({
      required this.id,
      required this.titulo,
      required this.artista,
      required this.descripcion,
      required this.adicional,
      required this.year,
      required this.tapaUrl,
    });
}

final albums = [
  Album(id: '1',
  titulo: 'The Black Parade', 
  artista: 'My Chemical Romance', 
  descripcion: 'Tercer album de estudio de My Chemical Roamance', 
  adicional: 'En este album se encuentra "Famous last words", una de mis canciones favoritas, y "Disenchanted", la cancion que Mikey Way le susurraba por las noches a su hermano para que la incluya en el álbum.', 
  year: 2006, 
  tapaUrl: 'https://upload.wikimedia.org/wikipedia/en/e/ea/Blackparadecover.jpg'),
  Album(id: '2',
  titulo: 'Danger Days: The True Lives of the Fabulous Killjoys', 
  artista: 'My Chemical Romance', 
  descripcion: 'Cuarto album de estudio de My Chemical Romance', 
  adicional: 'Después de un largo tiempo sin sacar albumes, My Chemical Romance hace un cambio de 180 grados y viene con un disco colorido y energético. Gerard Way incluso escribió cómics basándose en la narrativa del álbum.', 
  year: 2010, 
  tapaUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/51/Danger_Days-album-2010.jpg/250px-Danger_Days-album-2010.jpg'),
  Album(id: '3',
  titulo: 'Brand New Eyes', 
  artista: 'Paramore', 
  descripcion: 'Uno de los albumes más iconicos del pop punk', 
  adicional: 'Con canciones como "Ignorance" y "Brick by Boring Brick", Hayley Williams se considera una de las mejores "frontwomen" del genero.', 
  year: 2009, 
  tapaUrl: 'https://upload.wikimedia.org/wikipedia/en/9/9b/Paramore_-_Brand_New_Eyes.png'),
  Album(id: '4',
  titulo: 'BRAT', 
  artista: 'Charli XCX', 
  descripcion: 'El album que llevo al hyperpop al mainstream', 
  adicional: 'Charli XCX llega al lugar 16 en Metacritic con este album, y no sin razón. Aclamado tanto por la critica como por los fans, es un "club classic" moderno.', 
  year: 2024, 
  tapaUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/60/Charli_XCX_-_Brat_%28album_cover%29.png'),
  Album(id: '5',
  titulo: 'NO HANDS', 
  artista: 'Joey Valence & Brae', 
  descripcion: 'Nerd y energéticos, Joey y Brae vuelven a traer el sonido punk rap de los 90s', 
  adicional: 'Los "nuevos Beastie Boys" nos traen un album tanto nostálgico como moderno, lleno de referencias a la cultura pop, Joey y Brae se están instalando como los nuevos referentes del rap punk, llenando estadios y festivales con su energía y su estilo único.', 
  year: 2024, 
  tapaUrl: 'https://upload.wikimedia.org/wikipedia/en/e/ed/No_Hands_album_cover_by_Joey_Valence_%26_Brae.jpg'),
  Album(id: '6',
  titulo: 'From Under The Cork Tree', 
  artista: 'Fall Out Boy', 
  descripcion: 'EL segundo album de Fall Out Boy, con su lirisicmo característico aportado por Pete Wentz', 
  adicional: 'Lleno de canciones que se convirtieron en clásicos de la banda y la escena emo/scene de los 2000s, un "must listen" para los fans del genero. Dato curioso: la cancion "Our Lawyer Made Us Change the Name of This Song So We Wouldn\'t Get Sued" es literal. Le iban a poner un nombre que nombraba a otro cantante.', 
  year: 2005, 
  tapaUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXz0sxtgb24li-vCPvPpdvlRTCk9giBS2TUlqthsK6VQ&s=10'),
  Album(id: '7',
  titulo: 'Doolittle', 
  artista: 'Pixies', 
  descripcion: 'Un clasico indudable del rock alternativo, el impacto cultural de este album es innegable', 
  adicional: 'Con canciones como "Debaser" y "Monkey Gone to Heaven", este album es el fundador del sonido alternativo de los 90s. Su tapa, edmas, fue diseñada por Vaughan Oliver, quien diseño muchos otros discos iconicos de la epoca.', 
  year: 1989, 
  tapaUrl: 'https://upload.wikimedia.org/wikipedia/en/6/6b/Pixies-Doolittle.jpg'),
  Album(id: '8',
  titulo: 'Pretty Hate Machine', 
  artista: 'Nine Inch Nails', 
  descripcion: 'El debut de NIN, una marca imborrable del rock industrial', 
  adicional: 'Trent Reznor trabajaba en un estudio como técnico, y usaba su tiempo libre para grabar su propia música. No pensaba que llegaría a nada, pero su album fue muy bien recibido, llevandolo a la fama. LLego a hacer colaboraciones con grnades artistas, incluso haciendose amigo de David Lynch.', 
  year: 1989, 
  tapaUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f1/Nine_Inch_Nails_-_Pretty_Hate_Machine.png'),
  Album(id: '9',
  titulo: 'Crystal Castles', 
  artista: 'Crystal Castles', 
  descripcion: 'El debut auto titulado del duo, los pioneros del "darkwave".', 
  adicional: 'Crystal Castles es una banda que mezcla elementos de rock, electropop y darkwave. Su sonido único y su estética visual han hecho que sean una figura importante en la escena musical contemporánea.', 
  year: 2008, 
  tapaUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScQFsNTymRZ0zfD5__V65Q6CrhAlvFm2DS4RkwbxvgLgORPK7AhU2GSDY&s=10'),
  Album(id: '10',
  titulo: 'Violator', 
  artista: 'Depeche Mode', 
  descripcion: 'El album mas exitoso de la banda, un ícono del sythpop.', 
  adicional: 'Violator marca un antes y después no solo en Depeche Mode, sino en la música electrónica. Un album extremdadamente influyente y reconocido, con canciones como "Personal Jesus" y "Enjoy the Silence", que se volvieron clásicos del gótico.', 
  year: 1990, 
  tapaUrl: 'https://upload.wikimedia.org/wikipedia/en/9/92/Depeche_Mode_-_Violator.png'),
  Album(id: '11',
  titulo: 'Ultraviolence', 
  artista: 'Lana del Rey', 
  descripcion: 'Tercer album de Lana del Rey, laa icono del pop alternativo.', 
  adicional: 'Ultraviolence es un album que casi no fue. Después de "Born to Die", Lana dijo que no tenía intenciones de sacr otro album, pero en conjunto con Dan Aunerbach terminó siguiendo su carrera discográfica.', 
  year: 2014, 
  tapaUrl: 'https://upload.wikimedia.org/wikipedia/en/6/6a/UltraviolenceLDR.png'),
];